/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego;

/**
 *
 * @author Ñangie Reyes
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPlay = new javax.swing.JLabel();
        jLabelScore = new javax.swing.JLabel();
        jLabelQuit = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setName("frameMainMenu"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Texetura/play-hover.png"))); // NOI18N
        jLabelPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPlayMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 260, 150));

        jLabelScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Texetura/score.png"))); // NOI18N
        jLabelScore.setText("score");
        getContentPane().add(jLabelScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 300, 150));

        jLabelQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Texetura/quit.png"))); // NOI18N
        jLabelQuit.setText("quit");
        jLabelQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelQuitMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 280, 150));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Texetura/menu-principal.jpg"))); // NOI18N
        jLabelBackground.setPreferredSize(new java.awt.Dimension(720, 720));
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlayMouseClicked
        Nivel nivel1 = new Nivel();
        
        this.dispose();
        
        nivel1.setVisible(true);
    }//GEN-LAST:event_jLabelPlayMouseClicked

    private void jLabelQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuitMouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabelQuitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelPlay;
    private javax.swing.JLabel jLabelQuit;
    private javax.swing.JLabel jLabelScore;
    // End of variables declaration//GEN-END:variables
}
